name: flashback
channels:
  - anaconda
  - conda-forge
dependencies:
  - python
  - fire
  - black
  - gcsfs
  - cloudpathlib
  - google-cloud-pubsub
  - pylint
  - google-auth
  - pytest
  - pip
  - discord.py
  - jupyterlab
  - Pillow
  - pytesseract
  - scikit-image
  - matplotlib
  - numpy
  - opencv
  - keras-ocr
  - pip:
    - discord-webhook
