name: flashback
channels:
  - anaconda
  - conda-forge
dependencies:
  - python
  - fire
  - black
  - gcsfs
  - pylint
  - google-auth
  - pytest
  - discord.py
  - pillow
  - tk
  - numpy
  - pip
  - pip:
    - opencv-python
